included:
  - Source
  - Tests
  - UITests

disabled_rules:
  - explicit_type_interface
  - explicit_enum_raw_value

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - explicit_type_interface
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

superfluous_disable_command: warning
force_unwrapping: error
trailing_semicolon: error

line_length: 120
file_length:
  warning: 500
  error: 700

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

type_body_length:
  warning: 300
  error: 500

nesting:
  type_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    error: 3
  excluded:
    - i
    - id

custom_rules:
  double_space:
    include: "*.swift"
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning
  new_line_between_braces:
    include: "*.swift"
    name: "New line after }"
    regex: '\}\n\s*\n+\s*\}'
    message: "No new line between curly braces"
    severity: warning
