language: objective-c
osx_image: xcode9.4

branches:
  only:
    - master
    - develop

script:
  - xcodebuild clean test -workspace MockGenerator.xcworkspace -scheme MockGenerator -destination "platform=iOS Simulator,name=iPhone 8,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
