name: Deploy-Bot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Pr Build
      uses: Khan/pull-request-comment-trigger@1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        reaction: "rocket"
        trigger: "!build"
